# -*- coding: utf-8 -*-
"""Sistem Panen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ul_IQbZ6o8JdZC2JVSAT1re-j79K17fA
"""

"""
Program Penghitung Total Hasil Panen
Sistem Pencatatan Hasil Panen Digital
"""

def hitung_total_panen(data_panen):
    total = 0
    for panen in data_panen:
        total += panen["berat_kg"]
    return total


def hitung_harga_dengan_diskon(total_berat_kg, harga_per_kg, persen_diskon=0):
    harga_awal = total_berat_kg * harga_per_kg
    potongan = harga_awal * (persen_diskon / 100)
    harga_akhir = harga_awal - potongan
    return harga_akhir


def main():
    data_panen = [
        {"petak": "A1", "berat_kg": 120},
        {"petak": "A2", "berat_kg": 95},
        {"petak": "B1", "berat_kg": 150},
    ]
    total = hitung_total_panen(data_panen)

    print("=== Laporan Hasil Panen ===")
    for panen in data_panen:
        print(f"Petak {panen['petak']}: {panen['berat_kg']} kg")
    print(f"Total hasil panen: {total} kg")

    harga_per_kg = 5000
    persen_diskon = 10
    harga_akhir = hitung_harga_dengan_diskon(total, harga_per_kg, persen_diskon)
    print(f"Harga sebelum diskon: Rp{total * harga_per_kg:,}")
    print(f"Diskon: {persen_diskon}%")
    print(f"Harga setelah diskon: Rp{harga_akhir:,.0f}")


if __name__ == "__main__":
    main()