# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YdDcPlHQmZ_9-4axB10eHQHGk-9HUrp3
"""

!mkdir sistem-panen
!cd sistem-panen

!notepad panen.py

# Program Menghitung Total Hasil Panen

nama_tanaman = input("Masukkan nama tanaman: ")
jumlah_panen = float(input("Masukkan jumlah hasil panen (kg): "))
harga_per_kg = float(input("Masukkan harga per kg (Rp): "))

total_hasil = jumlah_panen * harga_per_kg

print("\n=== HASIL PANEN ===")
print("Tanaman       :", nama_tanaman)
print("Jumlah panen  :", jumlah_panen, "kg")
print("Harga per kg  : Rp", harga_per_kg)
print("Total hasil   : Rp", total_hasil)

!git init

!git add panen.py